unbind C-b
set -g prefix C-a

bind C-a send-prefix

# General

set -g mouse on
set -sg escape-time 10
set -g focus-events on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g history-limit 100000
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Binds

# bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind a select-pane -L
bind s select-pane -D
bind w select-pane -U
bind d select-pane -R

bind -r A resize-pane -L 5
bind -r S resize-pane -D 5
bind -r W resize-pane -U 5
bind -r D resize-pane -R 5

unbind ,
unbind .
bind , previous-window
bind . next-window

unbind r
bind r command-prompt -I "#W" "rename-window '%%'"

bind C-r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Status Bar

set -g status on
set -g status-position bottom

set -g @status_bg     "#222211"
set -g @status_fg     "#ffffee"
set -g @status_header "#774466"
set -g @status_prefix "#ff77ee"
set -g @status_host    "#40ff9a"
set -g @status_host_fg "#407bcf"
set -g @status_window  "#223355"
set -g @status_current "#339cff"
set -g @status_current_fg "#fdfddf"

set -g status-style "bg=#{@status_bg},fg=#{@status_fg}"

set -g status-left-length 40

set -g status-left \
'#[fg=#{@status_fg},bg=#{?client_prefix,#{@status_prefix},#{@status_header}},bold] tmux \
#[fg=#{?client_prefix,#{@status_prefix},#{@status_header}},bg=#{@status_host}] \
#[fg=#{@status_host_fg},bg=#{@status_host},nobold]#H \
#[fg=#{@status_host},bg=#{@status_bg}] '

set -g status-right ""

##### Windows #####

set -g window-status-separator " "

set -g window-status-format \
'#[fg=#{@status_window},bg=#{@status_bg}]\
#[fg=#{@status_fg},bg=#{@status_window}] #I:#W#F \
#[fg=#{@status_window},bg=#{@status_bg}]'

set -g window-status-current-format \
'#[fg=#{@status_current},bg=#{@status_bg}]\
#[fg=#{@status_current_fg},bg=#{@status_current},bold] #I:#W#F \
#[fg=#{@status_current},bg=#{@status_bg}]'

